train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../data/DIV2K_train_HR
      repeat: 20
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 8

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../data/DIV2K_valid_HR
      first_k: 10
      repeat: 160
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp_pw
      args:
        out_dim: 3
        hidden_list: [16, 16, 16, 16]
    pdn_spec:
      name: ExpansionNet
      args:
        in_dim: 580
        out_dim: 10
        hidden_list: [ 256, 256, 256, 256 ]
    basis_spec:
      name: basis
      args:
        basis_num: 10
        hidden: 16
        state: train
        path: ./save/test/epoch-last.pth
## pdn_spec[out_dim]==basis_spec[basis_num]
optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
